name: "Checks PR body for Assignment"
on:
  pull_request:
    types: [opened, edited]

jobs:
  check_pr:
      runs-on: ubuntu-latest
      steps:
        - name: Find Roll Number
          id: matcher
          uses: AsasInnab/regex-action@v1
          with:
            regex_pattern: '[0-9]{3}[A-Z]{2}[0-9]{3}'
        - name: Echo Roll Number
          run: echo "Is your roll number ${{ steps.jira.outputs.first_match }}?"
